# Dedicated Chatterbox streaming + voice-cloning API.

import logging
import os
import shutil
import tempfile
from pathlib import Path
from typing import Generator, Optional

import numpy as np
import torch
from fastapi import APIRouter, BackgroundTasks, File, Form, HTTPException, UploadFile
from fastapi.responses import StreamingResponse

import engine
from config import get_gen_default_cfg_weight

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/chatterbox/streaming", tags=["Chatterbox Streaming"])

DEFAULT_STREAM_CHUNK_SIZE = int(os.getenv("TTS_STREAM_DEFAULT_CHUNK_SIZE", "160"))


@router.get("/health")
async def streaming_health() -> dict:
    """Health endpoint for the dedicated streaming API."""
    return {
        "ok": True,
        "model_loaded": engine.MODEL_LOADED,
        "sample_rate": int(getattr(engine.chatterbox_model, "sr", 24000)) if engine.MODEL_LOADED else 24000,
    }


@router.post(
    "/voice-clone",
    summary="Stream TTS audio with optional voice cloning",
    description=(
        "Streams float32 PCM audio chunks generated by Chatterbox. "
        "Pass reference_audio for voice cloning; omit it to use default voice."
    ),
)
async def stream_voice_clone(
    background_tasks: BackgroundTasks,
    text: str = Form(..., description="Text to convert to speech"),
    reference_audio: Optional[UploadFile] = File(
        None,
        description="Optional reference voice audio (.wav/.mp3/.m4a/.flac/.ogg)",
    ),
    exaggeration: float = Form(0.5, description="Voice exaggeration (0.25-2.0)"),
    temperature: float = Form(0.8, description="Sampling temperature (0.05-5.0)"),
    cfg_weight: Optional[float] = Form(None, description="CFG weight (0.2-1.0)"),
    seed: int = Form(0, description="Random seed (0 = random)"),
    chunk_size: int = Form(
        DEFAULT_STREAM_CHUNK_SIZE,
        ge=10,
        le=500,
        description="Streaming token chunk size",
    ),
    language_id: Optional[str] = Form("en", description="Language code for multilingual model"),
    repetition_penalty: float = Form(1.2, description="Repetition penalty"),
    min_p: float = Form(0.05, description="Minimum probability sampler"),
    top_p: float = Form(1.0, description="Top-p/nucleus sampler"),
):
    if not text or not text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty")

    if not engine.MODEL_LOADED:
        raise HTTPException(status_code=503, detail="TTS model is not loaded")

    audio_prompt_path = None
    if reference_audio and reference_audio.filename:
        allowed_extensions = {".wav", ".mp3", ".m4a", ".flac", ".ogg"}
        ext = Path(reference_audio.filename).suffix.lower()
        if ext not in allowed_extensions:
            raise HTTPException(
                status_code=400,
                detail=(
                    f"Unsupported reference audio format: {ext}. "
                    f"Supported: {', '.join(sorted(allowed_extensions))}"
                ),
            )

        temp_ref = tempfile.NamedTemporaryFile(delete=False, suffix=ext)
        try:
            shutil.copyfileobj(reference_audio.file, temp_ref)
            temp_ref.close()
            audio_prompt_path = temp_ref.name
            background_tasks.add_task(lambda p: Path(p).unlink(missing_ok=True), temp_ref.name)
        except Exception as exc:
            logger.error("Failed to process uploaded reference audio", exc_info=True)
            raise HTTPException(status_code=400, detail=f"Failed to process reference audio: {exc}")
        finally:
            await reference_audio.close()

    cfg_weight = cfg_weight if cfg_weight is not None else get_gen_default_cfg_weight()

    logger.info(
        "Streaming request | text_len=%s | voice_clone=%s | language=%s | chunk_size=%s",
        len(text),
        bool(audio_prompt_path),
        language_id,
        chunk_size,
    )

    def audio_chunk_generator() -> Generator[bytes, None, None]:
        stream = engine.synthesize_stream(
            text=text,
            audio_prompt_path=audio_prompt_path,
            temperature=temperature,
            exaggeration=exaggeration,
            cfg_weight=cfg_weight,
            seed=seed,
            chunk_size=chunk_size,
            language_id=language_id,
            repetition_penalty=repetition_penalty,
            min_p=min_p,
            top_p=top_p,
        )

        # Keep small overlap blend to reduce chunk boundary artifacts.
        sample_rate = int(getattr(engine.chatterbox_model, "sr", 24000))
        crossfade_samples = int(0.02 * sample_rate)
        prev_tail = None

        for audio_chunk, _metrics in stream:
            if audio_chunk is None:
                continue

            if isinstance(audio_chunk, torch.Tensor):
                audio_np = audio_chunk.squeeze().detach().cpu().numpy().astype(np.float32)
            else:
                audio_np = np.asarray(audio_chunk, dtype=np.float32)

            if audio_np.size == 0:
                continue

            if (
                prev_tail is not None
                and crossfade_samples > 0
                and audio_np.size > crossfade_samples
                and prev_tail.size == crossfade_samples
            ):
                blended = prev_tail + audio_np[:crossfade_samples]
                body = audio_np[crossfade_samples:-crossfade_samples] if audio_np.size > 2 * crossfade_samples else np.array([], dtype=np.float32)
                chunk_out = np.concatenate([blended, body])
                if chunk_out.size > 0:
                    yield chunk_out.astype(np.float32, copy=False).tobytes()
                prev_tail = audio_np[-crossfade_samples:].copy()
            else:
                if crossfade_samples > 0 and audio_np.size > crossfade_samples:
                    yield audio_np[:-crossfade_samples].astype(np.float32, copy=False).tobytes()
                    prev_tail = audio_np[-crossfade_samples:].copy()
                else:
                    yield audio_np.astype(np.float32, copy=False).tobytes()
                    prev_tail = None

        if prev_tail is not None:
            fade_samples = min(prev_tail.size, crossfade_samples)
            if fade_samples > 0:
                fade_out = np.linspace(1.0, 0.0, fade_samples, dtype=np.float32)
                prev_tail[-fade_samples:] *= fade_out
            yield prev_tail.astype(np.float32, copy=False).tobytes()

    sample_rate = int(getattr(engine.chatterbox_model, "sr", 24000))
    return StreamingResponse(
        audio_chunk_generator(),
        media_type="application/octet-stream",
        headers={
            "X-Sample-Rate": str(sample_rate),
            "X-Encoding": "float32",
            "X-Channels": "1",
        },
    )
